# Forge
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# Syncopation
[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
version="${mod_version}"
description='''${mod_description}'''
authors="${mod_authors}"


# Mandatory dependencies
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"  # Loading order (NONE, BEFORE, AFTER)
side="BOTH"      # Mod side (BOTH, CLIENT, SERVER)

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"  # Loading order (NONE, BEFORE, AFTER)
side="BOTH"      # Mod side (BOTH, CLIENT, SERVER)


# Optional Dependencies (Integrations)